export interface WorkoutItem {
  name: string;
  category: string;
  caloriesPerMinute: number;
  intensity: 'low' | 'medium' | 'high';
  muscleGroups?: string[];
}

export const workoutDatabase: WorkoutItem[] = [
  // ========== CARDIO ==========
  { name: "Walking (slow, 2 mph)", category: "Cardio", caloriesPerMinute: 2.5, intensity: "low" },
  { name: "Walking (moderate, 3 mph)", category: "Cardio", caloriesPerMinute: 4, intensity: "low" },
  { name: "Walking (brisk, 3.5 mph)", category: "Cardio", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Walking (fast, 4 mph)", category: "Cardio", caloriesPerMinute: 5.5, intensity: "medium" },
  { name: "Power Walking", category: "Cardio", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Walking (uphill)", category: "Cardio", caloriesPerMinute: 6.5, intensity: "medium" },
  { name: "Running (5 mph / 12 min mile)", category: "Cardio", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Running (6 mph / 10 min mile)", category: "Cardio", caloriesPerMinute: 10, intensity: "medium" },
  { name: "Running (7 mph / 8.5 min mile)", category: "Cardio", caloriesPerMinute: 11.5, intensity: "high" },
  { name: "Running (8 mph / 7.5 min mile)", category: "Cardio", caloriesPerMinute: 13, intensity: "high" },
  { name: "Running (9 mph / 6.5 min mile)", category: "Cardio", caloriesPerMinute: 14.5, intensity: "high" },
  { name: "Running (10 mph / 6 min mile)", category: "Cardio", caloriesPerMinute: 16, intensity: "high" },
  { name: "Running (11 mph / 5.5 min mile)", category: "Cardio", caloriesPerMinute: 17.5, intensity: "high" },
  { name: "Running (12 mph / 5 min mile)", category: "Cardio", caloriesPerMinute: 19, intensity: "high" },
  { name: "Sprinting (all-out)", category: "Cardio", caloriesPerMinute: 20, intensity: "high" },
  { name: "Jogging", category: "Cardio", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Trail Running", category: "Cardio", caloriesPerMinute: 12, intensity: "high" },
  { name: "Interval Running", category: "Cardio", caloriesPerMinute: 12, intensity: "high" },
  { name: "Fartlek Training", category: "Cardio", caloriesPerMinute: 11, intensity: "high" },
  { name: "Treadmill (walking)", category: "Cardio", caloriesPerMinute: 4, intensity: "low" },
  { name: "Treadmill (running)", category: "Cardio", caloriesPerMinute: 10, intensity: "medium" },
  { name: "Treadmill (incline)", category: "Cardio", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Cycling (leisure, 10-12 mph)", category: "Cardio", caloriesPerMinute: 6, intensity: "low" },
  { name: "Cycling (moderate, 12-14 mph)", category: "Cardio", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Cycling (vigorous, 14-16 mph)", category: "Cardio", caloriesPerMinute: 10, intensity: "high" },
  { name: "Cycling (racing, 16+ mph)", category: "Cardio", caloriesPerMinute: 12, intensity: "high" },
  { name: "Mountain Biking", category: "Cardio", caloriesPerMinute: 9, intensity: "high" },
  { name: "BMX", category: "Cardio", caloriesPerMinute: 8, intensity: "high" },
  { name: "Stationary Bike (light)", category: "Cardio", caloriesPerMinute: 5, intensity: "low" },
  { name: "Stationary Bike (moderate)", category: "Cardio", caloriesPerMinute: 7.5, intensity: "medium" },
  { name: "Stationary Bike (vigorous)", category: "Cardio", caloriesPerMinute: 10, intensity: "high" },
  { name: "Spin Class", category: "Cardio", caloriesPerMinute: 11, intensity: "high" },
  { name: "Peloton Ride", category: "Cardio", caloriesPerMinute: 10, intensity: "high" },
  { name: "Air Bike (Assault Bike)", category: "Cardio", caloriesPerMinute: 15, intensity: "high" },
  { name: "Swimming (laps, slow)", category: "Cardio", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Swimming (laps, moderate)", category: "Cardio", caloriesPerMinute: 9, intensity: "medium" },
  { name: "Swimming (laps, vigorous)", category: "Cardio", caloriesPerMinute: 11, intensity: "high" },
  { name: "Swimming (freestyle)", category: "Cardio", caloriesPerMinute: 10, intensity: "high" },
  { name: "Swimming (backstroke)", category: "Cardio", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Swimming (breaststroke)", category: "Cardio", caloriesPerMinute: 10, intensity: "medium" },
  { name: "Swimming (butterfly)", category: "Cardio", caloriesPerMinute: 13, intensity: "high" },
  { name: "Treading Water", category: "Cardio", caloriesPerMinute: 4, intensity: "low" },
  { name: "Water Aerobics", category: "Cardio", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Water Jogging", category: "Cardio", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Lap Swimming (continuous)", category: "Cardio", caloriesPerMinute: 9, intensity: "medium" },
  { name: "Jump Rope (slow)", category: "Cardio", caloriesPerMinute: 10, intensity: "medium" },
  { name: "Jump Rope (moderate)", category: "Cardio", caloriesPerMinute: 12, intensity: "high" },
  { name: "Jump Rope (fast)", category: "Cardio", caloriesPerMinute: 14, intensity: "high" },
  { name: "Double Unders", category: "Cardio", caloriesPerMinute: 15, intensity: "high" },
  { name: "Rowing Machine (light)", category: "Cardio", caloriesPerMinute: 5, intensity: "low" },
  { name: "Rowing Machine (moderate)", category: "Cardio", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Rowing Machine (vigorous)", category: "Cardio", caloriesPerMinute: 11, intensity: "high" },
  { name: "Concept2 Rower", category: "Cardio", caloriesPerMinute: 10, intensity: "high" },
  { name: "Elliptical (light)", category: "Cardio", caloriesPerMinute: 5, intensity: "low" },
  { name: "Elliptical (moderate)", category: "Cardio", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Elliptical (vigorous)", category: "Cardio", caloriesPerMinute: 10, intensity: "high" },
  { name: "Stair Climber (slow)", category: "Cardio", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Stair Climber (moderate)", category: "Cardio", caloriesPerMinute: 9, intensity: "high" },
  { name: "Stair Climber (fast)", category: "Cardio", caloriesPerMinute: 12, intensity: "high" },
  { name: "StairMaster", category: "Cardio", caloriesPerMinute: 10, intensity: "high" },
  { name: "VersaClimber", category: "Cardio", caloriesPerMinute: 14, intensity: "high" },
  { name: "Ski Erg", category: "Cardio", caloriesPerMinute: 10, intensity: "high" },
  { name: "Arc Trainer", category: "Cardio", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Jacob's Ladder", category: "Cardio", caloriesPerMinute: 12, intensity: "high" },
  { name: "HIIT Workout", category: "Cardio", caloriesPerMinute: 12, intensity: "high" },
  { name: "Tabata Training", category: "Cardio", caloriesPerMinute: 14, intensity: "high" },
  { name: "Circuit Training", category: "Cardio", caloriesPerMinute: 10, intensity: "high" },
  { name: "Boot Camp Class", category: "Cardio", caloriesPerMinute: 11, intensity: "high" },
  { name: "Dance Cardio", category: "Cardio", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Zumba", category: "Cardio", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Aerobics (low impact)", category: "Cardio", caloriesPerMinute: 5, intensity: "low" },
  { name: "Aerobics (high impact)", category: "Cardio", caloriesPerMinute: 8, intensity: "high" },
  { name: "Step Aerobics", category: "Cardio", caloriesPerMinute: 9, intensity: "high" },
  { name: "Jazzercise", category: "Cardio", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Cardio Kickboxing", category: "Cardio", caloriesPerMinute: 10, intensity: "high" },
  { name: "Body Combat", category: "Cardio", caloriesPerMinute: 9, intensity: "high" },
  { name: "Barre Cardio", category: "Cardio", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Dance Dance Revolution", category: "Cardio", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Line Dancing", category: "Cardio", caloriesPerMinute: 4, intensity: "low" },
  { name: "Salsa Dancing", category: "Cardio", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Hip Hop Dance", category: "Cardio", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Ballet", category: "Cardio", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Pole Dancing", category: "Cardio", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Ballroom Dancing", category: "Cardio", caloriesPerMinute: 4, intensity: "low" },
  { name: "Jumping Jacks", category: "Cardio", caloriesPerMinute: 9, intensity: "medium" },
  { name: "High Knees", category: "Cardio", caloriesPerMinute: 10, intensity: "high" },
  { name: "Butt Kicks", category: "Cardio", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Marching in Place", category: "Cardio", caloriesPerMinute: 4, intensity: "low" },
  { name: "Shadow Boxing", category: "Cardio", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Rebounding (mini trampoline)", category: "Cardio", caloriesPerMinute: 6, intensity: "medium" },
  
  // ========== STRENGTH TRAINING - CHEST ==========
  { name: "Bench Press (barbell)", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Chest", "Triceps", "Shoulders"] },
  { name: "Bench Press (dumbbell)", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Chest", "Triceps", "Shoulders"] },
  { name: "Incline Bench Press (barbell)", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Upper Chest", "Shoulders", "Triceps"] },
  { name: "Incline Bench Press (dumbbell)", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Upper Chest", "Shoulders", "Triceps"] },
  { name: "Decline Bench Press", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Lower Chest", "Triceps"] },
  { name: "Close Grip Bench Press", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Triceps", "Chest"] },
  { name: "Floor Press", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Chest", "Triceps"] },
  { name: "Push-ups", category: "Strength Training", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Chest", "Triceps", "Core"] },
  { name: "Wide Push-ups", category: "Strength Training", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Chest", "Shoulders"] },
  { name: "Diamond Push-ups", category: "Strength Training", caloriesPerMinute: 7, intensity: "high", muscleGroups: ["Triceps", "Chest"] },
  { name: "Decline Push-ups", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Upper Chest", "Shoulders"] },
  { name: "Incline Push-ups", category: "Strength Training", caloriesPerMinute: 5, intensity: "low", muscleGroups: ["Lower Chest", "Triceps"] },
  { name: "Clapping Push-ups", category: "Strength Training", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Chest", "Triceps", "Shoulders"] },
  { name: "Archer Push-ups", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Chest", "Triceps"] },
  { name: "Spiderman Push-ups", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Chest", "Core", "Obliques"] },
  { name: "Pike Push-ups", category: "Strength Training", caloriesPerMinute: 7, intensity: "high", muscleGroups: ["Shoulders", "Triceps"] },
  { name: "Dumbbell Fly", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Chest"] },
  { name: "Incline Dumbbell Fly", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Upper Chest"] },
  { name: "Cable Fly", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Chest"] },
  { name: "Cable Crossover", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Chest"] },
  { name: "High Cable Crossover", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Lower Chest"] },
  { name: "Low Cable Crossover", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Upper Chest"] },
  { name: "Pec Deck Machine", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Chest"] },
  { name: "Chest Press Machine", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Chest", "Triceps"] },
  { name: "Incline Chest Press Machine", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Upper Chest", "Shoulders"] },
  { name: "Smith Machine Bench Press", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Chest", "Triceps"] },
  { name: "Dumbbell Pullover", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Chest", "Lats"] },
  { name: "Svend Press", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Chest"] },
  
  // ========== STRENGTH TRAINING - BACK ==========
  { name: "Pull-ups", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Back", "Biceps", "Core"] },
  { name: "Chin-ups", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Back", "Biceps"] },
  { name: "Wide Grip Pull-ups", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Lats", "Rhomboids"] },
  { name: "Close Grip Pull-ups", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Back", "Biceps"] },
  { name: "Neutral Grip Pull-ups", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Back", "Biceps"] },
  { name: "Assisted Pull-ups", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Back", "Biceps"] },
  { name: "Weighted Pull-ups", category: "Strength Training", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Back", "Biceps"] },
  { name: "Muscle-ups", category: "Strength Training", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Back", "Chest", "Triceps"] },
  { name: "Lat Pulldown", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Lats", "Biceps"] },
  { name: "Wide Grip Lat Pulldown", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Lats", "Rhomboids"] },
  { name: "Close Grip Lat Pulldown", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Lats", "Biceps"] },
  { name: "Reverse Grip Lat Pulldown", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Lats", "Biceps"] },
  { name: "Straight Arm Pulldown", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Lats"] },
  { name: "Seated Row", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Back", "Biceps", "Rhomboids"] },
  { name: "Seated Cable Row", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Back", "Biceps"] },
  { name: "Single Arm Cable Row", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Lats", "Biceps"] },
  { name: "Bent Over Row (barbell)", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Back", "Biceps", "Core"] },
  { name: "Bent Over Row (dumbbell)", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Back", "Biceps"] },
  { name: "Pendlay Row", category: "Strength Training", caloriesPerMinute: 6, intensity: "high", muscleGroups: ["Back", "Biceps"] },
  { name: "T-Bar Row", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Back", "Biceps"] },
  { name: "Chest Supported Row", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Back", "Biceps"] },
  { name: "Meadows Row", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Lats", "Biceps"] },
  { name: "One Arm Dumbbell Row", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Lats", "Biceps", "Rhomboids"] },
  { name: "Gorilla Row", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Back", "Core"] },
  { name: "Inverted Row", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Back", "Biceps"] },
  { name: "Kroc Row", category: "Strength Training", caloriesPerMinute: 5, intensity: "high", muscleGroups: ["Lats", "Grip"] },
  { name: "Seal Row", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Back"] },
  { name: "Face Pulls", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Rear Delts", "Upper Back", "Rotator Cuff"] },
  { name: "Reverse Fly", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Rear Delts", "Rhomboids"] },
  { name: "Cable Face Pull", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Rear Delts", "Upper Back"] },
  { name: "Shrugs (barbell)", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Traps"] },
  { name: "Shrugs (dumbbell)", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Traps"] },
  { name: "Rack Pulls", category: "Strength Training", caloriesPerMinute: 7, intensity: "high", muscleGroups: ["Back", "Traps", "Glutes"] },
  { name: "Good Mornings", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Lower Back", "Hamstrings", "Glutes"] },
  { name: "Back Extension", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Lower Back", "Glutes"] },
  { name: "Hyperextension", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Lower Back", "Glutes", "Hamstrings"] },
  { name: "Reverse Hyperextension", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Lower Back", "Glutes"] },
  { name: "Superman", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Lower Back", "Glutes"] },
  
  // ========== STRENGTH TRAINING - SHOULDERS ==========
  { name: "Overhead Press (barbell)", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Shoulders", "Triceps"] },
  { name: "Overhead Press (dumbbell)", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Shoulders", "Triceps"] },
  { name: "Seated Shoulder Press", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Shoulders", "Triceps"] },
  { name: "Standing Shoulder Press", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Shoulders", "Triceps", "Core"] },
  { name: "Arnold Press", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Shoulders", "Triceps"] },
  { name: "Push Press", category: "Strength Training", caloriesPerMinute: 7, intensity: "high", muscleGroups: ["Shoulders", "Triceps", "Legs"] },
  { name: "Military Press", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Shoulders", "Triceps"] },
  { name: "Behind the Neck Press", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Shoulders", "Triceps"] },
  { name: "Z Press", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Shoulders", "Core"] },
  { name: "Landmine Press", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Shoulders", "Chest"] },
  { name: "Shoulder Press Machine", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Shoulders"] },
  { name: "Smith Machine Shoulder Press", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Shoulders", "Triceps"] },
  { name: "Lateral Raises", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Side Delts"] },
  { name: "Lateral Raises (cable)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Side Delts"] },
  { name: "Lateral Raises (machine)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Side Delts"] },
  { name: "Front Raises", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Front Delts"] },
  { name: "Front Raises (barbell)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Front Delts"] },
  { name: "Front Raises (cable)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Front Delts"] },
  { name: "Rear Delt Fly", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Rear Delts"] },
  { name: "Rear Delt Machine", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Rear Delts"] },
  { name: "Upright Row", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Shoulders", "Traps"] },
  { name: "Upright Row (cable)", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Shoulders", "Traps"] },
  { name: "Lu Raises", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Front Delts", "Side Delts"] },
  { name: "Plate Front Raise", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Front Delts"] },
  { name: "Handstand Push-ups", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Shoulders", "Triceps"] },
  { name: "Wall Handstand Hold", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Shoulders", "Core"] },
  { name: "Cuban Press", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Rotator Cuff", "Shoulders"] },
  { name: "External Rotation", category: "Strength Training", caloriesPerMinute: 2, intensity: "low", muscleGroups: ["Rotator Cuff"] },
  { name: "Internal Rotation", category: "Strength Training", caloriesPerMinute: 2, intensity: "low", muscleGroups: ["Rotator Cuff"] },
  { name: "Bus Drivers", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Shoulders"] },
  
  // ========== STRENGTH TRAINING - ARMS ==========
  { name: "Bicep Curls (dumbbell)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Biceps"] },
  { name: "Bicep Curls (barbell)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Biceps"] },
  { name: "Bicep Curls (EZ bar)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Biceps"] },
  { name: "Bicep Curls (cable)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Biceps"] },
  { name: "Hammer Curls", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Biceps", "Forearms"] },
  { name: "Preacher Curls", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Biceps"] },
  { name: "Concentration Curls", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Biceps"] },
  { name: "Incline Dumbbell Curls", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Biceps"] },
  { name: "Spider Curls", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Biceps"] },
  { name: "21s Bicep Curls", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Biceps"] },
  { name: "Drag Curls", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Biceps"] },
  { name: "Reverse Curls", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Forearms", "Biceps"] },
  { name: "Zottman Curls", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Biceps", "Forearms"] },
  { name: "Cross Body Hammer Curls", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Biceps"] },
  { name: "Bayesian Curls", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Biceps"] },
  { name: "Tricep Dips", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Triceps", "Chest", "Shoulders"] },
  { name: "Bench Dips", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Triceps"] },
  { name: "Weighted Dips", category: "Strength Training", caloriesPerMinute: 7, intensity: "high", muscleGroups: ["Triceps", "Chest"] },
  { name: "Tricep Pushdown", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Triceps"] },
  { name: "Tricep Pushdown (rope)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Triceps"] },
  { name: "Tricep Pushdown (bar)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Triceps"] },
  { name: "Overhead Tricep Extension", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Triceps"] },
  { name: "Overhead Tricep Extension (dumbbell)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Triceps"] },
  { name: "Overhead Tricep Extension (cable)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Triceps"] },
  { name: "Skull Crushers", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Triceps"] },
  { name: "Skull Crushers (EZ bar)", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Triceps"] },
  { name: "Skull Crushers (dumbbell)", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Triceps"] },
  { name: "Tricep Kickbacks", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Triceps"] },
  { name: "JM Press", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Triceps"] },
  { name: "Tate Press", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Triceps"] },
  { name: "Wrist Curls", category: "Strength Training", caloriesPerMinute: 2, intensity: "low", muscleGroups: ["Forearms"] },
  { name: "Reverse Wrist Curls", category: "Strength Training", caloriesPerMinute: 2, intensity: "low", muscleGroups: ["Forearms"] },
  { name: "Farmer's Carry (forearm focus)", category: "Strength Training", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Forearms", "Grip"] },
  { name: "Plate Pinch", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Grip"] },
  { name: "Hand Gripper", category: "Strength Training", caloriesPerMinute: 2, intensity: "low", muscleGroups: ["Grip", "Forearms"] },
  { name: "Towel Pull-ups", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Grip", "Back"] },
  
  // ========== STRENGTH TRAINING - LEGS ==========
  { name: "Squats (barbell)", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Quads", "Glutes", "Hamstrings", "Core"] },
  { name: "Squats (dumbbell)", category: "Strength Training", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Quads", "Glutes", "Hamstrings"] },
  { name: "Squats (bodyweight)", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Quads", "Glutes"] },
  { name: "Front Squats", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Quads", "Core", "Upper Back"] },
  { name: "Goblet Squats", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Quads", "Glutes", "Core"] },
  { name: "Sumo Squats", category: "Strength Training", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Quads", "Glutes", "Adductors"] },
  { name: "Box Squats", category: "Strength Training", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Quads", "Glutes", "Hamstrings"] },
  { name: "Pause Squats", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Quads", "Glutes"] },
  { name: "Overhead Squats", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Quads", "Core", "Shoulders"] },
  { name: "Zercher Squats", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Quads", "Core", "Biceps"] },
  { name: "Anderson Squats", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Quads", "Glutes"] },
  { name: "Safety Bar Squats", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Quads", "Glutes"] },
  { name: "Hack Squat", category: "Strength Training", caloriesPerMinute: 7, intensity: "high", muscleGroups: ["Quads", "Glutes"] },
  { name: "Smith Machine Squats", category: "Strength Training", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Quads", "Glutes"] },
  { name: "Leg Press", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Quads", "Glutes", "Hamstrings"] },
  { name: "Leg Press (wide stance)", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Glutes", "Adductors"] },
  { name: "Leg Press (narrow stance)", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Quads"] },
  { name: "Deadlift (conventional)", category: "Strength Training", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Back", "Hamstrings", "Glutes", "Quads"] },
  { name: "Deadlift (sumo)", category: "Strength Training", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Glutes", "Quads", "Hamstrings", "Back"] },
  { name: "Romanian Deadlift", category: "Strength Training", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Hamstrings", "Glutes", "Lower Back"] },
  { name: "Stiff Leg Deadlift", category: "Strength Training", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Hamstrings", "Glutes", "Lower Back"] },
  { name: "Single Leg Romanian Deadlift", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Hamstrings", "Glutes", "Balance"] },
  { name: "Trap Bar Deadlift", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Quads", "Glutes", "Back"] },
  { name: "Deficit Deadlift", category: "Strength Training", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Back", "Hamstrings", "Glutes"] },
  { name: "Block Deadlift", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Back", "Traps"] },
  { name: "Jefferson Deadlift", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Quads", "Glutes", "Core"] },
  { name: "Snatch Grip Deadlift", category: "Strength Training", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Back", "Traps", "Hamstrings"] },
  { name: "Lunges (walking)", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Quads", "Glutes", "Hamstrings"] },
  { name: "Lunges (stationary)", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Quads", "Glutes"] },
  { name: "Lunges (reverse)", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Quads", "Glutes"] },
  { name: "Lunges (lateral)", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Quads", "Glutes", "Adductors"] },
  { name: "Lunges (curtsy)", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Glutes", "Quads"] },
  { name: "Bulgarian Split Squat", category: "Strength Training", caloriesPerMinute: 7, intensity: "high", muscleGroups: ["Quads", "Glutes"] },
  { name: "Split Squats", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Quads", "Glutes"] },
  { name: "Step-ups", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Quads", "Glutes"] },
  { name: "Step-ups (weighted)", category: "Strength Training", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Quads", "Glutes"] },
  { name: "Step-ups (lateral)", category: "Strength Training", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Glutes", "Abductors"] },
  { name: "Leg Extensions", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Quads"] },
  { name: "Leg Curls (lying)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Hamstrings"] },
  { name: "Leg Curls (seated)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Hamstrings"] },
  { name: "Leg Curls (standing)", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Hamstrings"] },
  { name: "Nordic Curls", category: "Strength Training", caloriesPerMinute: 6, intensity: "high", muscleGroups: ["Hamstrings"] },
  { name: "Glute Ham Raise", category: "Strength Training", caloriesPerMinute: 6, intensity: "high", muscleGroups: ["Hamstrings", "Glutes"] },
  { name: "Hip Thrusts (barbell)", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Glutes", "Hamstrings"] },
  { name: "Hip Thrusts (dumbbell)", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Glutes"] },
  { name: "Hip Thrusts (banded)", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Glutes"] },
  { name: "Single Leg Hip Thrust", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Glutes"] },
  { name: "Glute Bridge", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Glutes"] },
  { name: "Glute Bridge (single leg)", category: "Strength Training", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Glutes"] },
  { name: "Cable Kickbacks", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Glutes"] },
  { name: "Donkey Kicks", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Glutes"] },
  { name: "Fire Hydrants", category: "Strength Training", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Glutes", "Abductors"] },
  { name: "Clamshells", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Glutes", "Abductors"] },
  { name: "Hip Abduction Machine", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Abductors"] },
  { name: "Hip Adduction Machine", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Adductors"] },
  { name: "Cable Hip Abduction", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Abductors"] },
  { name: "Sumo Deadlift High Pull", category: "Strength Training", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Glutes", "Back", "Shoulders"] },
  { name: "Sissy Squats", category: "Strength Training", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Quads"] },
  { name: "Pistol Squats", category: "Strength Training", caloriesPerMinute: 7, intensity: "high", muscleGroups: ["Quads", "Glutes", "Balance"] },
  { name: "Calf Raises (standing)", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Calves"] },
  { name: "Calf Raises (seated)", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Calves"] },
  { name: "Calf Raises (machine)", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Calves"] },
  { name: "Calf Raises (donkey)", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Calves"] },
  { name: "Calf Raises (single leg)", category: "Strength Training", caloriesPerMinute: 3, intensity: "low", muscleGroups: ["Calves"] },
  { name: "Tibialis Raise", category: "Strength Training", caloriesPerMinute: 2, intensity: "low", muscleGroups: ["Tibialis"] },
  
  // ========== CORE ==========
  { name: "Planks", category: "Core", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Core", "Shoulders"] },
  { name: "Side Planks", category: "Core", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Obliques", "Core"] },
  { name: "Plank with Shoulder Taps", category: "Core", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Core", "Shoulders"] },
  { name: "Plank Jacks", category: "Core", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Core", "Cardio"] },
  { name: "Plank to Push-up", category: "Core", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Core", "Triceps"] },
  { name: "RKC Plank", category: "Core", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Core"] },
  { name: "Hollow Body Hold", category: "Core", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Core"] },
  { name: "Arch Body Hold", category: "Core", caloriesPerMinute: 4, intensity: "medium", muscleGroups: ["Lower Back", "Glutes"] },
  { name: "Crunches", category: "Core", caloriesPerMinute: 5, intensity: "low", muscleGroups: ["Abs"] },
  { name: "Reverse Crunches", category: "Core", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Lower Abs"] },
  { name: "Bicycle Crunches", category: "Core", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Abs", "Obliques"] },
  { name: "Cable Crunches", category: "Core", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Abs"] },
  { name: "Sit-ups", category: "Core", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Abs", "Hip Flexors"] },
  { name: "V-ups", category: "Core", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Abs"] },
  { name: "Tuck-ups", category: "Core", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Abs"] },
  { name: "Leg Raises (hanging)", category: "Core", caloriesPerMinute: 6, intensity: "high", muscleGroups: ["Lower Abs", "Hip Flexors"] },
  { name: "Leg Raises (lying)", category: "Core", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Lower Abs"] },
  { name: "Leg Raises (captain's chair)", category: "Core", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Lower Abs"] },
  { name: "Knee Raises (hanging)", category: "Core", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Lower Abs"] },
  { name: "Toes to Bar", category: "Core", caloriesPerMinute: 7, intensity: "high", muscleGroups: ["Abs", "Lats"] },
  { name: "Windshield Wipers", category: "Core", caloriesPerMinute: 7, intensity: "high", muscleGroups: ["Obliques", "Abs"] },
  { name: "Russian Twists", category: "Core", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Obliques"] },
  { name: "Russian Twists (weighted)", category: "Core", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Obliques"] },
  { name: "Woodchoppers", category: "Core", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Obliques", "Core"] },
  { name: "Cable Woodchoppers", category: "Core", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Obliques"] },
  { name: "Pallof Press", category: "Core", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Core", "Anti-rotation"] },
  { name: "Mountain Climbers", category: "Core", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Core", "Shoulders", "Cardio"] },
  { name: "Dead Bug", category: "Core", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Core"] },
  { name: "Bird Dog", category: "Core", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Core", "Lower Back"] },
  { name: "Ab Wheel Rollout", category: "Core", caloriesPerMinute: 6, intensity: "high", muscleGroups: ["Core", "Shoulders", "Lats"] },
  { name: "Barbell Rollout", category: "Core", caloriesPerMinute: 6, intensity: "high", muscleGroups: ["Core", "Shoulders"] },
  { name: "Stability Ball Rollout", category: "Core", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Core"] },
  { name: "Stability Ball Crunch", category: "Core", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Abs"] },
  { name: "Dragon Flag", category: "Core", caloriesPerMinute: 7, intensity: "high", muscleGroups: ["Abs", "Core"] },
  { name: "L-Sit", category: "Core", caloriesPerMinute: 5, intensity: "high", muscleGroups: ["Core", "Hip Flexors"] },
  { name: "L-Sit Hold", category: "Core", caloriesPerMinute: 5, intensity: "high", muscleGroups: ["Core", "Triceps"] },
  { name: "Plank Variations", category: "Core", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Core"] },
  { name: "Flutter Kicks", category: "Core", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Lower Abs"] },
  { name: "Scissor Kicks", category: "Core", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Lower Abs"] },
  { name: "In and Outs", category: "Core", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Abs"] },
  { name: "Ab Crunch Machine", category: "Core", caloriesPerMinute: 4, intensity: "low", muscleGroups: ["Abs"] },
  { name: "Decline Sit-ups", category: "Core", caloriesPerMinute: 6, intensity: "medium", muscleGroups: ["Abs"] },
  { name: "GHD Sit-ups", category: "Core", caloriesPerMinute: 7, intensity: "high", muscleGroups: ["Abs", "Hip Flexors"] },
  
  // ========== MARTIAL ARTS ==========
  { name: "Boxing", category: "Martial Arts", caloriesPerMinute: 11, intensity: "high" },
  { name: "Boxing (heavy bag)", category: "Martial Arts", caloriesPerMinute: 9, intensity: "high" },
  { name: "Boxing (speed bag)", category: "Martial Arts", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Boxing (sparring)", category: "Martial Arts", caloriesPerMinute: 12, intensity: "high" },
  { name: "Boxing (pad work)", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "Boxing (shadow boxing)", category: "Martial Arts", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Boxing (technique drills)", category: "Martial Arts", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Kickboxing", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "Kickboxing (sparring)", category: "Martial Arts", caloriesPerMinute: 12, intensity: "high" },
  { name: "Kickboxing (bag work)", category: "Martial Arts", caloriesPerMinute: 9, intensity: "high" },
  { name: "Muay Thai", category: "Martial Arts", caloriesPerMinute: 11, intensity: "high" },
  { name: "Muay Thai (pad work)", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "Muay Thai (sparring)", category: "Martial Arts", caloriesPerMinute: 13, intensity: "high" },
  { name: "Muay Thai (clinch work)", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "Muay Thai (technique)", category: "Martial Arts", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Karate", category: "Martial Arts", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Karate (kata)", category: "Martial Arts", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Karate (kumite/sparring)", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "Shotokan Karate", category: "Martial Arts", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Kyokushin Karate", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "Goju-Ryu Karate", category: "Martial Arts", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Taekwondo", category: "Martial Arts", caloriesPerMinute: 9, intensity: "high" },
  { name: "Taekwondo (sparring)", category: "Martial Arts", caloriesPerMinute: 11, intensity: "high" },
  { name: "Taekwondo (forms/poomsae)", category: "Martial Arts", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Taekwondo (kicking drills)", category: "Martial Arts", caloriesPerMinute: 8, intensity: "high" },
  { name: "Judo", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "Judo (randori/sparring)", category: "Martial Arts", caloriesPerMinute: 12, intensity: "high" },
  { name: "Judo (uchikomi/throwing drills)", category: "Martial Arts", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Judo (newaza/ground work)", category: "Martial Arts", caloriesPerMinute: 9, intensity: "high" },
  { name: "Brazilian Jiu-Jitsu (BJJ)", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "BJJ (rolling/sparring)", category: "Martial Arts", caloriesPerMinute: 12, intensity: "high" },
  { name: "BJJ (drilling)", category: "Martial Arts", caloriesPerMinute: 7, intensity: "medium" },
  { name: "BJJ (positional sparring)", category: "Martial Arts", caloriesPerMinute: 9, intensity: "high" },
  { name: "BJJ (gi)", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "BJJ (no-gi)", category: "Martial Arts", caloriesPerMinute: 11, intensity: "high" },
  { name: "Wrestling", category: "Martial Arts", caloriesPerMinute: 11, intensity: "high" },
  { name: "Wrestling (live wrestling)", category: "Martial Arts", caloriesPerMinute: 13, intensity: "high" },
  { name: "Wrestling (drilling)", category: "Martial Arts", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Freestyle Wrestling", category: "Martial Arts", caloriesPerMinute: 12, intensity: "high" },
  { name: "Greco-Roman Wrestling", category: "Martial Arts", caloriesPerMinute: 12, intensity: "high" },
  { name: "Folkstyle Wrestling", category: "Martial Arts", caloriesPerMinute: 11, intensity: "high" },
  { name: "MMA Training", category: "Martial Arts", caloriesPerMinute: 12, intensity: "high" },
  { name: "MMA Sparring", category: "Martial Arts", caloriesPerMinute: 14, intensity: "high" },
  { name: "MMA Striking", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "MMA Grappling", category: "Martial Arts", caloriesPerMinute: 11, intensity: "high" },
  { name: "MMA Ground and Pound", category: "Martial Arts", caloriesPerMinute: 12, intensity: "high" },
  { name: "MMA Conditioning", category: "Martial Arts", caloriesPerMinute: 13, intensity: "high" },
  { name: "Kung Fu", category: "Martial Arts", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Kung Fu (forms)", category: "Martial Arts", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Kung Fu (sparring)", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "Wing Chun", category: "Martial Arts", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Wing Chun (chi sao)", category: "Martial Arts", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Wushu", category: "Martial Arts", caloriesPerMinute: 9, intensity: "high" },
  { name: "Sanda (Chinese Kickboxing)", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "Sanda (sparring)", category: "Martial Arts", caloriesPerMinute: 12, intensity: "high" },
  { name: "Aikido", category: "Martial Arts", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Hapkido", category: "Martial Arts", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Krav Maga", category: "Martial Arts", caloriesPerMinute: 11, intensity: "high" },
  { name: "Krav Maga (self-defense drills)", category: "Martial Arts", caloriesPerMinute: 9, intensity: "high" },
  { name: "Krav Maga (stress drills)", category: "Martial Arts", caloriesPerMinute: 12, intensity: "high" },
  { name: "Capoeira", category: "Martial Arts", caloriesPerMinute: 9, intensity: "high" },
  { name: "Capoeira (roda)", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "Sambo", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "Sambo (combat)", category: "Martial Arts", caloriesPerMinute: 12, intensity: "high" },
  { name: "Jeet Kune Do", category: "Martial Arts", caloriesPerMinute: 9, intensity: "high" },
  { name: "Kendo", category: "Martial Arts", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Kendo (sparring)", category: "Martial Arts", caloriesPerMinute: 10, intensity: "high" },
  { name: "Iaido", category: "Martial Arts", caloriesPerMinute: 4, intensity: "low" },
  { name: "Fencing", category: "Martial Arts", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Fencing (bout)", category: "Martial Arts", caloriesPerMinute: 9, intensity: "high" },
  { name: "Escrima/Kali/Arnis", category: "Martial Arts", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Silat", category: "Martial Arts", caloriesPerMinute: 8, intensity: "high" },
  { name: "Savate (French Kickboxing)", category: "Martial Arts", caloriesPerMinute: 9, intensity: "high" },
  { name: "Sumo Training", category: "Martial Arts", caloriesPerMinute: 8, intensity: "high" },
  { name: "Systema", category: "Martial Arts", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Lethwei (Burmese Boxing)", category: "Martial Arts", caloriesPerMinute: 12, intensity: "high" },
  { name: "Pradal Serey", category: "Martial Arts", caloriesPerMinute: 11, intensity: "high" },
  { name: "Pencak Silat", category: "Martial Arts", caloriesPerMinute: 8, intensity: "high" },
  { name: "Vovinam", category: "Martial Arts", caloriesPerMinute: 8, intensity: "high" },
  { name: "Tai Chi", category: "Martial Arts", caloriesPerMinute: 3, intensity: "low" },
  { name: "Tai Chi (Chen style)", category: "Martial Arts", caloriesPerMinute: 4, intensity: "low" },
  { name: "Tai Chi (Yang style)", category: "Martial Arts", caloriesPerMinute: 3, intensity: "low" },
  { name: "Qigong", category: "Martial Arts", caloriesPerMinute: 2, intensity: "low" },
  { name: "Ba Gua Zhang", category: "Martial Arts", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Xing Yi Quan", category: "Martial Arts", caloriesPerMinute: 6, intensity: "medium" },
  
  // ========== SPORTS ==========
  { name: "Basketball", category: "Sports", caloriesPerMinute: 8, intensity: "high" },
  { name: "Basketball (game)", category: "Sports", caloriesPerMinute: 9, intensity: "high" },
  { name: "Basketball (shooting around)", category: "Sports", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Soccer", category: "Sports", caloriesPerMinute: 9, intensity: "high" },
  { name: "Soccer (game)", category: "Sports", caloriesPerMinute: 10, intensity: "high" },
  { name: "Soccer (practice)", category: "Sports", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Football (American)", category: "Sports", caloriesPerMinute: 9, intensity: "high" },
  { name: "Football (practice)", category: "Sports", caloriesPerMinute: 7, intensity: "high" },
  { name: "Tennis (singles)", category: "Sports", caloriesPerMinute: 8, intensity: "high" },
  { name: "Tennis (doubles)", category: "Sports", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Pickleball", category: "Sports", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Badminton", category: "Sports", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Volleyball", category: "Sports", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Volleyball (beach)", category: "Sports", caloriesPerMinute: 8, intensity: "high" },
  { name: "Hockey (ice)", category: "Sports", caloriesPerMinute: 9, intensity: "high" },
  { name: "Hockey (field)", category: "Sports", caloriesPerMinute: 8, intensity: "high" },
  { name: "Hockey (roller)", category: "Sports", caloriesPerMinute: 8, intensity: "high" },
  { name: "Baseball (game)", category: "Sports", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Softball", category: "Sports", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Golf (walking, carrying clubs)", category: "Sports", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Golf (with cart)", category: "Sports", caloriesPerMinute: 3, intensity: "low" },
  { name: "Golf (driving range)", category: "Sports", caloriesPerMinute: 3, intensity: "low" },
  { name: "Table Tennis", category: "Sports", caloriesPerMinute: 4, intensity: "low" },
  { name: "Racquetball", category: "Sports", caloriesPerMinute: 9, intensity: "high" },
  { name: "Squash", category: "Sports", caloriesPerMinute: 10, intensity: "high" },
  { name: "Handball", category: "Sports", caloriesPerMinute: 10, intensity: "high" },
  { name: "Rugby", category: "Sports", caloriesPerMinute: 10, intensity: "high" },
  { name: "Cricket", category: "Sports", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Lacrosse", category: "Sports", caloriesPerMinute: 8, intensity: "high" },
  { name: "Rock Climbing (indoor)", category: "Sports", caloriesPerMinute: 8, intensity: "high" },
  { name: "Rock Climbing (outdoor)", category: "Sports", caloriesPerMinute: 9, intensity: "high" },
  { name: "Bouldering", category: "Sports", caloriesPerMinute: 8, intensity: "high" },
  { name: "Skateboarding", category: "Sports", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Rollerblading", category: "Sports", caloriesPerMinute: 8, intensity: "high" },
  { name: "Ice Skating", category: "Sports", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Roller Skating", category: "Sports", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Surfing", category: "Sports", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Paddleboarding", category: "Sports", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Kayaking", category: "Sports", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Canoeing", category: "Sports", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Rowing (boat)", category: "Sports", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Water Polo", category: "Sports", caloriesPerMinute: 10, intensity: "high" },
  { name: "Snowboarding", category: "Sports", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Skiing (downhill)", category: "Sports", caloriesPerMinute: 7, intensity: "high" },
  { name: "Skiing (cross-country)", category: "Sports", caloriesPerMinute: 10, intensity: "high" },
  { name: "Snowshoeing", category: "Sports", caloriesPerMinute: 8, intensity: "medium" },
  { name: "Figure Skating", category: "Sports", caloriesPerMinute: 7, intensity: "medium" },
  { name: "Speed Skating", category: "Sports", caloriesPerMinute: 12, intensity: "high" },
  { name: "Frisbee", category: "Sports", caloriesPerMinute: 4, intensity: "low" },
  { name: "Ultimate Frisbee", category: "Sports", caloriesPerMinute: 8, intensity: "high" },
  { name: "Disc Golf", category: "Sports", caloriesPerMinute: 4, intensity: "low" },
  { name: "Bowling", category: "Sports", caloriesPerMinute: 3, intensity: "low" },
  { name: "Archery", category: "Sports", caloriesPerMinute: 3, intensity: "low" },
  { name: "Horseback Riding (walking)", category: "Sports", caloriesPerMinute: 4, intensity: "low" },
  { name: "Horseback Riding (trotting)", category: "Sports", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Horseback Riding (galloping)", category: "Sports", caloriesPerMinute: 8, intensity: "high" },
  { name: "Boxing (workout)", category: "Sports", caloriesPerMinute: 10, intensity: "high" },
  
  // ========== FLEXIBILITY & RECOVERY ==========
  { name: "Yoga (Hatha)", category: "Flexibility", caloriesPerMinute: 3, intensity: "low" },
  { name: "Yoga (Vinyasa)", category: "Flexibility", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Yoga (Power)", category: "Flexibility", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Yoga (Ashtanga)", category: "Flexibility", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Yoga (Bikram/Hot)", category: "Flexibility", caloriesPerMinute: 7, intensity: "high" },
  { name: "Yoga (Yin)", category: "Flexibility", caloriesPerMinute: 2, intensity: "low" },
  { name: "Yoga (Restorative)", category: "Flexibility", caloriesPerMinute: 2, intensity: "low" },
  { name: "Yoga (Iyengar)", category: "Flexibility", caloriesPerMinute: 3, intensity: "low" },
  { name: "Yoga (Kundalini)", category: "Flexibility", caloriesPerMinute: 4, intensity: "medium" },
  { name: "Yoga (Rocket)", category: "Flexibility", caloriesPerMinute: 6, intensity: "high" },
  { name: "Yoga (Core Power)", category: "Flexibility", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Pilates (mat)", category: "Flexibility", caloriesPerMinute: 4, intensity: "medium" },
  { name: "Pilates (reformer)", category: "Flexibility", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Barre", category: "Flexibility", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Stretching (general)", category: "Flexibility", caloriesPerMinute: 2, intensity: "low" },
  { name: "Stretching (dynamic)", category: "Flexibility", caloriesPerMinute: 3, intensity: "low" },
  { name: "Stretching (static)", category: "Flexibility", caloriesPerMinute: 2, intensity: "low" },
  { name: "Stretching (PNF)", category: "Flexibility", caloriesPerMinute: 2, intensity: "low" },
  { name: "Foam Rolling", category: "Flexibility", caloriesPerMinute: 2, intensity: "low" },
  { name: "Mobility Work", category: "Flexibility", caloriesPerMinute: 3, intensity: "low" },
  { name: "Active Recovery", category: "Flexibility", caloriesPerMinute: 3, intensity: "low" },
  { name: "Massage (self-myofascial release)", category: "Flexibility", caloriesPerMinute: 2, intensity: "low" },
  { name: "Lacrosse Ball Myofascial Release", category: "Flexibility", caloriesPerMinute: 2, intensity: "low" },
  { name: "Contrast Therapy", category: "Flexibility", caloriesPerMinute: 2, intensity: "low" },
  { name: "Warm-up", category: "Flexibility", caloriesPerMinute: 4, intensity: "low" },
  { name: "Cool-down", category: "Flexibility", caloriesPerMinute: 2, intensity: "low" },
  
  // ========== FUNCTIONAL TRAINING ==========
  { name: "CrossFit WOD", category: "Functional", caloriesPerMinute: 12, intensity: "high" },
  { name: "CrossFit (AMRAP)", category: "Functional", caloriesPerMinute: 11, intensity: "high" },
  { name: "CrossFit (EMOM)", category: "Functional", caloriesPerMinute: 10, intensity: "high" },
  { name: "CrossFit (Chipper)", category: "Functional", caloriesPerMinute: 11, intensity: "high" },
  { name: "CrossFit (Hero WOD)", category: "Functional", caloriesPerMinute: 12, intensity: "high" },
  { name: "Kettlebell Swings", category: "Functional", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Glutes", "Hamstrings", "Core", "Shoulders"] },
  { name: "Kettlebell Swings (one-arm)", category: "Functional", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Glutes", "Core"] },
  { name: "Kettlebell Snatch", category: "Functional", caloriesPerMinute: 11, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Kettlebell Clean", category: "Functional", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Kettlebell Clean and Press", category: "Functional", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Kettlebell Turkish Get-up", category: "Functional", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Full Body", "Core"] },
  { name: "Kettlebell Goblet Squat", category: "Functional", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Quads", "Glutes"] },
  { name: "Kettlebell Windmill", category: "Functional", caloriesPerMinute: 5, intensity: "medium", muscleGroups: ["Core", "Shoulders"] },
  { name: "Kettlebell Farmer's Walk", category: "Functional", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Grip", "Core"] },
  { name: "Battle Ropes", category: "Functional", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Shoulders", "Core", "Arms"] },
  { name: "Battle Ropes (alternating waves)", category: "Functional", caloriesPerMinute: 10, intensity: "high" },
  { name: "Battle Ropes (slams)", category: "Functional", caloriesPerMinute: 11, intensity: "high" },
  { name: "Box Jumps", category: "Functional", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Quads", "Glutes", "Calves"] },
  { name: "Box Step-ups", category: "Functional", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Quads", "Glutes"] },
  { name: "Broad Jumps", category: "Functional", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Quads", "Glutes"] },
  { name: "Depth Jumps", category: "Functional", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Quads", "Glutes"] },
  { name: "Burpees", category: "Functional", caloriesPerMinute: 11, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Burpees (with push-up)", category: "Functional", caloriesPerMinute: 12, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Burpee Box Jumps", category: "Functional", caloriesPerMinute: 13, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Medicine Ball Slams", category: "Functional", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Core", "Shoulders", "Lats"] },
  { name: "Medicine Ball Wall Balls", category: "Functional", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Quads", "Shoulders"] },
  { name: "Medicine Ball Throws", category: "Functional", caloriesPerMinute: 8, intensity: "medium", muscleGroups: ["Core", "Chest"] },
  { name: "Medicine Ball Rotational Throws", category: "Functional", caloriesPerMinute: 8, intensity: "medium", muscleGroups: ["Core", "Obliques"] },
  { name: "Tire Flips", category: "Functional", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Tire Sledgehammer", category: "Functional", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Core", "Arms"] },
  { name: "Farmer's Walk", category: "Functional", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Grip", "Core", "Traps"] },
  { name: "Farmer's Walk (heavy)", category: "Functional", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Grip", "Core", "Full Body"] },
  { name: "Suitcase Carry", category: "Functional", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Grip", "Core", "Obliques"] },
  { name: "Overhead Carry", category: "Functional", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Shoulders", "Core"] },
  { name: "Zercher Carry", category: "Functional", caloriesPerMinute: 7, intensity: "medium", muscleGroups: ["Core", "Biceps"] },
  { name: "Yoke Walk", category: "Functional", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Sled Push", category: "Functional", caloriesPerMinute: 11, intensity: "high", muscleGroups: ["Quads", "Glutes", "Core"] },
  { name: "Sled Pull", category: "Functional", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Back", "Biceps", "Hamstrings"] },
  { name: "Sled Drag", category: "Functional", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Prowler Push", category: "Functional", caloriesPerMinute: 12, intensity: "high", muscleGroups: ["Quads", "Glutes"] },
  { name: "Sandbag Training", category: "Functional", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Sandbag Clean", category: "Functional", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Sandbag Carry", category: "Functional", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Full Body", "Core"] },
  { name: "Strongman Training", category: "Functional", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Atlas Stones", category: "Functional", caloriesPerMinute: 11, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Log Press", category: "Functional", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Shoulders", "Triceps"] },
  { name: "Circus Dumbbell", category: "Functional", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Shoulders", "Core"] },
  
  // ========== OLYMPIC LIFTING ==========
  { name: "Clean and Jerk", category: "Olympic Lifting", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Power Clean", category: "Olympic Lifting", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Hang Clean", category: "Olympic Lifting", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Clean Pull", category: "Olympic Lifting", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Back", "Traps", "Hamstrings"] },
  { name: "Snatch", category: "Olympic Lifting", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Power Snatch", category: "Olympic Lifting", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Hang Snatch", category: "Olympic Lifting", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Snatch Pull", category: "Olympic Lifting", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Back", "Traps"] },
  { name: "Overhead Squat", category: "Olympic Lifting", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Quads", "Core", "Shoulders"] },
  { name: "Split Jerk", category: "Olympic Lifting", caloriesPerMinute: 9, intensity: "high", muscleGroups: ["Shoulders", "Legs"] },
  { name: "Push Jerk", category: "Olympic Lifting", caloriesPerMinute: 8, intensity: "high", muscleGroups: ["Shoulders", "Legs"] },
  { name: "Thruster", category: "Olympic Lifting", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Quads", "Shoulders"] },
  { name: "Cluster", category: "Olympic Lifting", caloriesPerMinute: 10, intensity: "high", muscleGroups: ["Full Body"] },
  { name: "Muscle Clean", category: "Olympic Lifting", caloriesPerMinute: 8, intensity: "medium", muscleGroups: ["Shoulders", "Traps"] },
  { name: "Muscle Snatch", category: "Olympic Lifting", caloriesPerMinute: 8, intensity: "medium", muscleGroups: ["Shoulders", "Traps"] },
  
  // ========== OTHER ACTIVITIES ==========
  { name: "Hiking (flat terrain)", category: "Other", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Hiking (moderate hills)", category: "Other", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Hiking (steep/mountainous)", category: "Other", caloriesPerMinute: 8, intensity: "high" },
  { name: "Hiking (with backpack)", category: "Other", caloriesPerMinute: 7, intensity: "high" },
  { name: "Backpacking", category: "Other", caloriesPerMinute: 8, intensity: "high" },
  { name: "Orienteering", category: "Other", caloriesPerMinute: 9, intensity: "high" },
  { name: "Gardening (light)", category: "Other", caloriesPerMinute: 3, intensity: "low" },
  { name: "Gardening (heavy)", category: "Other", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Yard Work", category: "Other", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Raking Leaves", category: "Other", caloriesPerMinute: 4, intensity: "low" },
  { name: "Mowing Lawn (push mower)", category: "Other", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Mowing Lawn (riding)", category: "Other", caloriesPerMinute: 2, intensity: "low" },
  { name: "Shoveling Snow", category: "Other", caloriesPerMinute: 7, intensity: "high" },
  { name: "Chopping Wood", category: "Other", caloriesPerMinute: 6, intensity: "medium" },
  { name: "House Cleaning (light)", category: "Other", caloriesPerMinute: 3, intensity: "low" },
  { name: "House Cleaning (vigorous)", category: "Other", caloriesPerMinute: 4, intensity: "medium" },
  { name: "Vacuuming", category: "Other", caloriesPerMinute: 3, intensity: "low" },
  { name: "Mopping", category: "Other", caloriesPerMinute: 4, intensity: "low" },
  { name: "Scrubbing Floors", category: "Other", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Washing Dishes", category: "Other", caloriesPerMinute: 2, intensity: "low" },
  { name: "Laundry", category: "Other", caloriesPerMinute: 2, intensity: "low" },
  { name: "Cooking", category: "Other", caloriesPerMinute: 2, intensity: "low" },
  { name: "Moving Furniture", category: "Other", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Carrying Boxes", category: "Other", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Moving (packing/unpacking)", category: "Other", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Playing with Kids (active)", category: "Other", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Playing with Kids (moderate)", category: "Other", caloriesPerMinute: 3, intensity: "low" },
  { name: "Walking the Dog", category: "Other", caloriesPerMinute: 4, intensity: "low" },
  { name: "Standing (light activity)", category: "Other", caloriesPerMinute: 2, intensity: "low" },
  { name: "Seated Work", category: "Other", caloriesPerMinute: 1, intensity: "low" },
  { name: "Walking at Work", category: "Other", caloriesPerMinute: 3, intensity: "low" },
  { name: "Stocking Shelves", category: "Other", caloriesPerMinute: 4, intensity: "medium" },
  { name: "Construction Work", category: "Other", caloriesPerMinute: 6, intensity: "high" },
  { name: "Firefighting", category: "Other", caloriesPerMinute: 10, intensity: "high" },
  { name: "Police Training", category: "Other", caloriesPerMinute: 8, intensity: "high" },
  { name: "Military Training", category: "Other", caloriesPerMinute: 10, intensity: "high" },
  { name: "Obstacle Course", category: "Other", caloriesPerMinute: 11, intensity: "high" },
  { name: "Spartan Race Training", category: "Other", caloriesPerMinute: 11, intensity: "high" },
  { name: "Tough Mudder Training", category: "Other", caloriesPerMinute: 11, intensity: "high" },
  { name: "Ninja Warrior Training", category: "Other", caloriesPerMinute: 10, intensity: "high" },
  { name: "Parkour", category: "Other", caloriesPerMinute: 10, intensity: "high" },
  { name: "Trampoline", category: "Other", caloriesPerMinute: 6, intensity: "medium" },
  { name: "Hula Hooping", category: "Other", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Jump Roping (recreational)", category: "Other", caloriesPerMinute: 10, intensity: "medium" },
  { name: "Sex (active)", category: "Other", caloriesPerMinute: 5, intensity: "medium" },
  { name: "Meditation", category: "Other", caloriesPerMinute: 1, intensity: "low" },
  { name: "Sleep", category: "Other", caloriesPerMinute: 0.9, intensity: "low" },
];

export function searchWorkouts(query: string): WorkoutItem[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return [];
  
  return workoutDatabase.filter(workout => 
    workout.name.toLowerCase().includes(lowerQuery) ||
    workout.category.toLowerCase().includes(lowerQuery) ||
    (workout.muscleGroups && workout.muscleGroups.some(mg => mg.toLowerCase().includes(lowerQuery)))
  ).slice(0, 25);
}

export function getWorkoutsByCategory(category: string): WorkoutItem[] {
  return workoutDatabase.filter(workout => workout.category === category);
}

export function getAllWorkoutCategories(): string[] {
  return [...new Set(workoutDatabase.map(workout => workout.category))];
}

export function calculateCaloriesBurned(caloriesPerMinute: number, durationMinutes: number, weight: number = 70): number {
  const weightFactor = weight / 70;
  return Math.round(caloriesPerMinute * durationMinutes * weightFactor);
}
